server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.254.130:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.254.130
  rabbitmq:
    host: 192.168.254.130
aliyun:
  sms:
    AccessKeyId: LTAIG3ZBaWeDg49D
    AccessKeySecret: CZEjPtmIGT44A1PlLTY0uhztQf9gBC
    sign_name: 练宏
    template_code: SMS_142616397
jwt:
  config:
    key: kelly
    ttl: 3600000
